#!/usr/bin/env bash

git submodule init
git submodule update
pushd env/.config/nvim
git checkout main
popd

mkdir -p $HOME/personal

pushd $HOME/personal/

git clone https://github.com/robhorbury/package-transfer
git clone https://github.com/robhorbury/venv-lookup

popd
