#!/usr/bin/env bash

brew install --cask amethyst

defaults write com.apple.dock workspaces-auto-swoosh -bool NO
killall Dock

defaults write com.amethyst.Amethyst windowMargins -bool true
defaults write com.amethyst.Amethyst SUEnableAutomaticChecks -bool true

killall Amethyst
open -a Amethyst

