#!/usr/bin/env bash

brew install git ripgrep python3-pip python@3.9 python@3.10 python@3.11 python@3.12 python@3.13 zoxide

git clone https://github.com/junegunn/fzf $HOME/personal/fzf
$HOME/personal/fzf/install
