#!/usr/bin/env bash

brew install cmake gettext lua5.1 liblua5.1-0-dev
brew install ripgrep fzf


if [ ! -d $HOME/neovim ]; then
    git clone https://github.com/neovim/neovim.git $HOME/neovim
fi

git -C ~/neovim fetch --all
git -C ~/neovim checkout v0.10.4

make -C ~/neovim clean
make -C ~/neovim CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make -C ~/neovim install

rm -rf ~/neovim

