#!/bin/bash

SESSION="quick-terminal"

# Check if session exists
tmux has-session -t $SESSION 2>/dev/null

if [ $? != 0 ]; then
  # Create new session with background color env variable
  tmux new-session -d -s $SESSION "exec \$SHELL"
fi

# Attach to the session
tmux attach-session -t $SESSION
