#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

has_session() {
    tmux has-session -t "$1" 2>/dev/null
}

hydrate() {
    local session="$1"
    local dir="$2"

    # Skip if in excluded directory
    if [[ "$dir" == "$HOME/personal/dev" ]]; then
        return
    fi

    # Check if the "scratch" window already exists
    if ! tmux list-windows -t "$session" | grep -q "^.*scratch"; then
        # Create a new window named "scratch" and run `nvim` and clear
        tmux new-window -dn scratch -c "$dir" "nvim .; clear"
    fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/personal ~/personal/dev ~/work/asda ~/work -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
    exit 0
fi

if ! has_session "$selected_name"; then
    tmux new-session -ds "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
fi

switch_to "$selected_name"

