layouts:
  - fullscreen
  - bsp
  - tall

mod1:
  - option
  - shift

mod2:
  - option
  - control

floating:
  - com.apple.systempreferences
  - com.apple.finder

custom-actions:
  minimize-focused-window:
    shell: osascript -e 'tell application "System Events" to keystroke "m" using {command down}'

key-bindings:
  minimize-window:
    mod: mod1
    key: b
    action: custom-actions.minimize-focused-window



window-margins: true
window-margin-size: 6

mouse-follows-focus: false
focus-follows-mouse: false

