#!/usr/bin/env bash

# Set global git configs:
git config --global user.name "Rob Horbury"

git config --global core.editor "nvim"
git config --global rerere.enabled true
git config --global push.autoSetupRemote true
git config --global init.defaultBranch main
git config --global submodule.recurse true
git config --global branch.sort -committerdate
git config --global http.sslbackend openssl
git config --global http.postbuffer 500000000
git config --global http.sslverify true
git config --global core.excludeFiles $XDG_CONFIG_HOME/git/ignore

# Diff tool config
git config --global diff.tool nvimdiff
git config --global difftool.nvimdiff.cmd 'nvim -d "$LOCAL" "$REMOTE"'
git config --global difftool.prompt false

# Merge tool config
git config --global merge.tool nvimdiff
git config --global mergetool.nvimdiff.cmd 'nvim -d "$LOCAL" "$MERGED" "$REMOTE"'
git config --global mergetool.prompt false

# In these two locations, I want to use custom git configs:
git config --global includeif.gitdir:"~/work/asda/**.path" ~/work/asda/.gitconfig
git config --global includeif.gitdir:"~/personal/**.path" ~/personal/.gitconfig


# Setup ssh if not existing, first personal:
if [ -f "$HOME/.ssh/github-personal" ]; then
  echo "personal SSH key exists"
else
  echo "Creating personal ssh key"
  ssh-keygen -t ed25519 -f ~/.ssh/github-personal
fi

# Then for asda
if [ -f "$HOME/.ssh/github-asda" ]; then
  echo "Asda SSH key exists"
else
  echo "Creating asda ssh key"
  ssh-keygen -t ed25519 -f ~/.ssh/github-asda
fi
